# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --prod

    - name: Get git commit hash
      run: git rev-parse HEAD
      id: git_commit

    - name: Replace version with git commit hash
      run: |
        commit_hash=$(echo ${{steps.git_commit.outputs.stdout}} | tr -d '\n')
        sed -i "s/{{version}}/$commit_hash/g" dist/index.html

    - name: Deploy
      run: echo "Deploying to production..."


